### PR TITLE
Add automated alembic tree integrity check on `pre-push` git hook

### PR DESCRIPTION
**Pull request by rennat**
We have had a few simple-yet-time-consuming issues from a branching alembic version tree.

This pull request adds a `ci/check_alembic_integrity.py` executable script that will return an error code if any of the following conditions are met:

- any alembic version file's `revision` identifier does not match the identifier in the file name
- more than one `root` revision is present
- more than one `head` revision is present

This script is called in `ci/test_pre_push.sh` (which is called when before pushing and also from the circle-ci entrypoint `ci/test.sh`)

⚠️ This PR adds a dependency on the MIT-Licensed python library `pyprinttree`, installable via PyPi. It also adds this to the `requirements.txt`. This allows us to render a `git log --graph`-like structure to diagnose and fix issues with the alembic tree.

---

basic usage:

```
# valid example (exit code 0)
$ cd raw-data-repository
$ ci/check_alembic_integrity.py
Checking integrity of Alembic tree... VALID
```

```
# invalid example (exit code 1)
$ cd raw-data-repository
$ ci/check_alembic_integrity.py
Checking integrity of Alembic tree... INVALID

Alembic tree has more than one HEAD: [edb6d45e5e45_revision_a.py, 0cc3557c43d0_revision_c.py]
```

graph visualization:

```
# valid example (exit code 0)
$ cd raw-data-repository
$ ci/check_alembic_integrity.py --graph
Checking integrity of Alembic tree... VALID
* ae11bf43cab2_initial_schema.py
* edb6d45e5e45_revision_a.py
* 3d4a6433e26d_revision_b.py
* 0cc3557c43d0_revision_c.py
```

```
# invalid example (exit code 1)
$ cd raw-data-repository
$ ci/check_alembic_integrity.py --graph
Checking integrity of Alembic tree... INVALID
* ae11bf43cab2_initial_schema.py
|\
| * edb6d45e5e45_revision_a.py
* 3d4a6433e26d_revision_b.py
* 0cc3557c43d0_revision_c.py

Alembic tree has more than one HEAD: [edb6d45e5e45_revision_a.py, 0cc3557c43d0_revision_c.py]
```

### CODE REVIEW

**Comment by robabram** [comment]
Have you reviewed the new python module license to verify it is one we already have approval for? License list is located in ci/license_whitelist.txt.  If its not, a PD ticket needs to be created to get a security team review and approval.

**Comment by rennat** [comment]
> Have you reviewed the new python module license to verify it is one we already have approval for? License list is located in ci/license_whitelist.txt. If its not, a PD ticket needs to be created to get a security team review and approval.

yes the MIT License is listed in the whitelist file.

**Comment by robabram** [comment]
Does this script check against the HEAD branch or just the current branch?

**Comment by rennat** [comment]
> Does this script check against the HEAD branch or just the current branch?

It checks the current working tree

**Comment by rennat** [comment]
Since this PR isn't blocking any tickets, I'm going to let it hang out open for a while.

**Comment by robabram** [comment]
Sorry, I meant Master branch. I was thinking it would be cool if it also would check against the HEAD in the Master branch.  Somehow simulate the merge of the Alembic migration version directory and run the check.  Maybe thats too much trouble.

**Comment by rennat** [comment]
That would make this much more useful! I'll play around with it, there should be a way to do this

**Comment by rennat** [comment]
I'm going to leave this open as `work in progress` until we can get back to taking the current `master` branch into account with the current working tree. Until then if you want to use the checking script you can `git checkout origin/tn/alembic-integrity-check -- ../ci/check_alembic_integrity.py`

**Comment by Seeker1911** [comment]
still a WIP ?

**Comment by rennat** [comment]
deleting this pull request since it is outdated now

**Pull request closed without merging**
