### PR TITLE
DA-1515 update gror not sure values

### PR DESCRIPTION
**Pull request by Seeker1911**
Refactored genomic consent to accept an "unsure" response. 
Updated tests to match.
Removed some of the legacy PyCharm tools.

### CODE REVIEW

**Comment by wangy70** [comment]
Are you sure you want to submit all your IDE runConfigurations files?

**Comment by Seeker1911** [comment]
The `.idea` directory is already shared in our project.
most of these are just deleting the old version of the tools we use.

**Comment by wangy70** [comment]
It seems you remove all the content of those files. Why?

**Comment by wangy70** [comment]
I think some of them are still in use, like Unittests__Partial.xml , I use it for unit test.

**Comment by Seeker1911** [comment]
I had two unittests_partial. One that works and one that assumes the old directory structure. Are you sure you use that particular one ?

**Comment by wangy70** [comment]
Yes, I double checked, I use Unittests__Partial.xml, and I believe Robert also use this one.

**Review by wangy70 — APPROVED** [review]

**Pull request merged**
