### PR TITLE
Making setup_env work on Ubuntu desktops.

### PR DESCRIPTION
**Pull request by danqrodney**
(OS X should be unaffected.)

### CODE REVIEW

**Comment by calbach** [comment]
I don't think OSTYPE is the right trigger:

```
(try-dan-rodete) [15:52][rest-api((HEAD detached at origin/danrodney/env_fix))]$ tools/setup_env.sh 
Removing old libs...
Cleaning up artifacts (pyo, pyc, etc)...
Installing libs...

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --system
```

**Comment by danqrodney** [comment]
You did this on your Ubuntu box in a venv?

Can you run pip --version?

**Comment by calbach** [comment]
Yep

```
pip --version
pip 10.0.1 from /usr/local/google/home/calbach/.virtualenvs/try-dan-rodete/local/lib/python2.7/site-packages/pip (python 2.7)
```

**Comment by danqrodney** [comment]
Ah. When I do it (in a venv), I get:

pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

I don't know why 1) my pip is older or 2) why it isn't grabbing pip from a virtualenv like it is for you. Do you know?

**Comment by Seeker1911** [comment]
check your activate script in bin/ grep for `VIRTUAL_ENV` and see if thats the right path,
otherwise, destroy the venv and recreate it

**Comment by johnstill** [comment]
@danqrodney what is the output of `echo $VIRTUAL_ENV`?  I suspect that (A) the env is activated improperly or inactive or (B) the virtual env creation tool used did not bootstrap `pip` into the virtual environment (some older tools didn't, but they should all do that by default now).

If its the former, you can try de- and then re-activating the environment (or even destroying and recreating it).  If its the latter, I recommend you install `virtualenvwrapper` (you should be able to get it via apt-get).  It will prefix the environment name to your prompt so you always know if the env is activated and gives you a bunch of convenience commands, and it should always bootstrap pip when you create an environment.

**Comment by johnstill** [comment]
Also if OSTYPE doesn't work reliably you should be able to use `[[ $(uname -s) = 'Linux' ]]` (it'll be 'Darwin' for OS X).

**Comment by danqrodney** [comment]
Starting with a new venv fixed my issues. I'm closing this.

**Pull request closed without merging**
