### PR TITLE
[DA-983] Support generating spec test participants

### PR DESCRIPTION
**Pull request by robabram**
Added spec version of participant generator.
Added python version of random participant generator.

### CODE REVIEW

**Comment by Seeker1911** [comment]
removed random from codacy errors

**Comment by Seeker1911** [comment]
Looks good, albeit very different from our current process's. Could you add documentation on how to use the new tools ?

**Comment by robabram** [comment]
Yes, there is documentation in the README.MD file.  I'll also add some documentation to the playbook.

**Comment by Seeker1911** [comment]
I don't see this in README

**Comment by robabram** [comment]
Its in the "rest-api/client_cli/README.md" file, which is in the other "Foundation" PR.

**Pull request merged**
