### PR TITLE
Add multiple fhirclient library versions to project

### PR DESCRIPTION
**Pull request by robabram**

### CODE REVIEW

**Comment by robabram** [comment]
Codacy issues are `assert` calls in the fhirclient library and also complaining about the bash lines gathering files for linting.

**Comment by Seeker1911** [comment]
I've removed `assert` condition from Codacy, the issue that it would cause doesn't apply to RDR anyway.

**Comment by Seeker1911** [comment]
would it possible to add the fhir client's as git sub-modules ?

**Comment by robabram** [comment]
I hadn't thought about sub-modules, but it should be fine.

**Comment by robabram** [comment]
Its not possible to add Git Tag branches as sub-modules.  This is the best way to add multiple versions of the fhirclient library.

**Pull request merged**
